### ISSUE TITLE
Variants not working on win32

### ISSUE THREAD

**Issue by foresterLV** [gittup/tup#70] opened 2012-06-01 16:53 UTC
It seems variants feature explained in manual is not working on win32. Tup detects variant directory and reports any issues in config file, but when running "tup upd" no targets are built at all.

**Comment by Manuzor** [comment] 2015-09-08 15:05
Any news on this?

**Comment by amosbird** [comment] 2015-10-10 12:32
I'm running into the same issue. Hope it will be fixed soon.

**Comment by blueberrysensationalhouse** [comment] 2015-10-13 17:20
Can you guys try the 'explicit-variant' branch? https://github.com/gittup/tup/tree/explicit-variant

See this thread for some additional details: https://groups.google.com/forum/#!searchin/tup-users/variants/tup-users/UNUSE15PQdA/B2xTM68QCwAJ

**Comment by gittup** [comment] 2015-10-13 17:23
Can you guys try the 'explicit-variant' branch? https://github.com/gittup/tup/tree/explicit-variant

See this thread for more details: https://groups.google.com/forum/#!searchin/tup-users/variants/tup-users/UNUSE15PQdA/B2xTM68QCwAJ

**Comment by amosbird** [comment] 2015-10-14 02:10
@gittup I would love to test this branch. However, there is little info I can find to build tup on Windows.

**Comment by gittup** [comment] 2015-10-14 19:54
I'm not sure if tup does build locally on Windows. I generate the Windows builds by cross-compiling from Linux with this in my tup.config:

CONFIG_TUP_MINGW=x86_64-w64-mingw32
CONFIG_TUP_MINGW32=i686-w64-mingw32

I rebased the explicit-variant branch against master and published a Windows build here: http://gittup.org/tup/win32/tup-explicit-variant.zip

I'm sure there are going to be issues, so let me know what you run across!

**Comment by amosbird** [comment] 2015-10-15 02:16
After changing to this tup, the building process cannot find its header files
```
../../../src/storage/test.cc:3:27: fatal error: easylogging++.h: No such file or directory
compilation terminated.
```
I'm sure using previous tup it would build.

**Comment by KamilSzczygiel** [comment] 2015-10-15 07:47
If you want some help with that, it would be useful to post the exact rule from Tupfile that should compile the file (with other relevant Tupfile fragments), the command that was executed and info about location of all needed files. I'm pretty sure that you should use different include path style in case of variants and probably that is your problem here.

**Comment by gittup** [comment] 2015-10-16 02:26
Yeah, if you can show your Tupfile (or even better, reduce it to a small example that shows the problem), that would help! Note that in this branch, the variants are not as transparent as they are with the FUSE overlay. You may need to add something like '-I$(TUP_SRCDIR)' to your commands to get them to work with variants. But if it's just failing to build now even without variants, that sounds like a bug.

**Comment by amosbird** [comment] 2015-10-16 09:31
I have `CFLAGS += -I$(TUP_CWD)/src/include` in my Tupfile and `easylogging++.h` in that directory. In fact I'v already found a usable [Tup](https://github.com/njubee/tup) build that supports variant on Windows, and this build works fine. So I may say it is a bug.

**Comment by KamilSzczygiel** [comment] 2015-10-16 09:34
Having `$(TUP_CWD)` directly in the CFLAGS makes no sense as this will always be "." (unless this line is in Tuprules file). You have to use a variable from Tuprules file for that:

in Tuprules

    TOP=$(TUP_CWD)

in Tupfile

    CFLAGS += -I$(TOP)/src/include

**Comment by amosbird** [comment] 2015-10-16 09:36
@KamilSzczygiel ops, it's in my Tuprules. Thanks for pointing it out.

**Comment by KamilSzczygiel** [comment] 2015-10-16 11:40
I'm not sure whether:
A. you had that line in Tuprules, it didn't work and it still doesn't work
B. you didn't had that line in Tuprules, it didn't work, but with the changes I suggested it works fine now

**Comment by amosbird** [comment] 2015-10-16 12:41
@KamilSzczygiel 
A

**Comment by gittup** [comment] 2015-10-16 17:34
@amosbird In the explicit-variant branch, you may need to add $(TUP_SRCDIR) elements to the path. So instead of -I$(TUP_CWD)/src/include it would be -I$(TUP_SRCDIR)/$(TUP_CWD)/src/include.

That seems a bit messy though, so perhaps $(TUP_SRCDIR) should somewhat mimic $(TUP_CWD) when it's included in Tuprules.tup files. I will need to think about that some more.

I also missed that @njubee got variants working on Windows anyway. Should I just be merging that instead? That would get us up and running here, though I may still want to consider explicit-variants in order to simplify the dependency checker and pave the way for the shared library shim in OSX.

**Comment by gittup** [comment] 2015-11-05 18:49
I tried to use this with the gittup.org repos and found it difficult. I think the issue is that the explicit-variant branch was running all subprocesses in the variant directory, and pulling in source files. This made it hard to find additional sources in the source directory.

I updated the explicit-variant branch to instead run all subprocesses in the source directory, and direct the outputs to the variant directory. To use it, all Tupfiles should be mostly written as if variants don't exist. For example, this Tupfile:

: foreach *.c |> gcc -c %f -o %o |> %B.o
: *.o |> gcc %f -o %o |> prog.exe

Works fine in a variant:
$ mkdir build
$ touch build/tup.config
$ tup
[ tup ] [0.051s] Executing Commands...
 1) [0.035s] [build] gcc -c main.c -o build/main.o
 2) [0.035s] [build] gcc -c foo.c -o build/foo.o
 3) [0.039s] [build] gcc build/foo.o build/main.o -o build/prog.exe
 [   ] 100%
[ tup ] [0.140s] Updated.

Note that tup just changes how it expands %o, %f, etc when using a variant. However, things get a little tricky when the subprocess needs to use a generated file that isn't expanded by %f, such as a generated header. For example, this works without a variant:

: |> echo '#define FOO 3' > %o |> foo.h
: foreach *.c | foo.h |> gcc -I. -c %f -o %o |> %B.o
: *.o |> gcc %f -o %o |> prog.exe

(where foo.c includes "foo.h")

But inside a variant it can't find foo.h:

* 3) [build] gcc -I. -c foo.c -o build/foo.o                                                                                                                 
foo.c:1:17: fatal error: foo.h: No such file or directory
 #include "foo.h"

This is because -I. references the source directory, but the header file is actually in the variant directory. To fix this, we can use the $(TUP_VARIANTDIR) variable:

: |> echo '#define FOO 3' > %o |> foo.h
: foreach *.c | foo.h |> gcc -I$(TUP_VARIANTDIR) -c %f -o %o |> %B.o
: *.o |> gcc %f -o %o |> prog.exe

Inside a variant, it expands to something like 'build', while without variants, it just expands to '.'. It can be used similar to $(TUP_CWD) in a Tuprules.tup file:

Tuprules.tup:
# For non-generated header files:
MYPROJ_ROOT = $(TUP_CWD)
CFLAGS += -I$(MYPROJ_ROOT)/include

# For generated header files:
MYPROJ_OUTPUT = $(TUP_VARIANTDIR)
CFLAGS += -I$(MYPROJ_OUTPUT)/include

With these changes, I was able to update both tup and the gittup.org repos to build with explicit variants, though they did require some tweaking to use $(TUP_VARIANTDIR) in the appropriate places. However, the benefit to doing this is that paths are accurate for things like gcov, and you can copy/paste a command to run it manually like you could for a non-variant build.

Note that $(TUP_SRCDIR) is gone in this version, since that is effectively what $(TUP_CWD) is.

Windows binaries are here: http://gittup.org/tup/win32/tup-explicit-variant-v0.7.3-45-gcf6a829.zip

Any feedback would be appreciated!

**Comment by cfillion** [comment] 2016-02-26 23:26
> Any feedback would be appreciated!

I've been using that version (v0.7.3-45-gcf6a829) for a while now on windows with TUP_VARIANTDIR, it works quite well!
Any chance to see this merged in the default tup builds?

**Comment by DPD85** [comment] 2017-02-08 11:06
I'm also very interest to have the variants to works on Windows, I think will be very useful.
So any news on that?

**Comment by lindquist** [comment] 2017-08-07 08:53
Indeed variants not working on Windows is quite the deal-breaker

**Comment by pbl-pw** [comment] 2018-10-05 05:56
Does FUSE for Windows make things easy?
https://github.com/billziss-gh/winfsp

**Comment by gittup** [comment] 2021-05-17 18:39
Explicit variants have been merged to the master branch, which now work on Windows.

**Closed by gittup** 2021-05-17 18:39 UTC
