### ISSUE TITLE
Generating a compile_commands.json file

### ISSUE THREAD

**Issue by xpac27** [gittup/tup#342] opened 2017-12-30 14:19 UTC
Could Tup emit a compile_commands.json file to use with Vim's YouCompleteMe plugin and other clang/llvm based tools? I know Ninja and CMake can do it so maybe it would not be to much work adding that feature to Tup. What do you think?

**Comment by adzenith** [comment] 2018-01-05 20:53
There's a thread about this here:
https://groups.google.com/d/topic/tup-users/AfP0ouHRqGY/discussion

**Comment by gittup** [comment] 2018-01-16 20:19
I think it'd be a good feature to add, and I'd be happy to merge it if someone wants to try to implement it.

**Comment by xpac27** [comment] 2018-01-16 22:04
I tried the patch linked in that google groups discussion. It produces an incomplet json and needs more work or be done differently. I'm trying to look into [mar...'s sugestion](https://groups.google.com/d/msg/tup-users/AfP0ouHRqGY/5zh__OJLEgAJ). Any advice from anyone familiar with tup's code would be much welcome 😅

**Comment by gittup** [comment] 2018-01-17 20:48
As far as the parser code, I think it might make sense in do_rule(). I'm not totally sure this is the correct place to do it, but here's an example patch that prints out the expanded command string, and loops through input files that would be used in the '%f' marker, which are probably candidates for the "file" attribute in the json output.

```
diff --git a/src/tup/parser.c b/src/tup/parser.c
index 789c86a..3ff8361 100644
--- a/src/tup/parser.c
+++ b/src/tup/parser.c
@@ -3240,6 +3240,12 @@ static int do_rule(struct tupfile *tf, struct rule *r, struct name_list *nl,
 		return -1;
 	free(tcmd);
 
+	printf("CMD: %s\n", cmd);
+	TAILQ_FOREACH(nle, &nl->entries, list) {
+		printf(" - Possible 'file' entry: %s/", get_tup_top());
+		print_tup_entry(stdout, nle->tent);
+		printf("\n");
+	}
 	if(cs.display) {
 		real_display = tup_printf(tf, cs.display, cs.displaylen, nl, &onl, &r->order_only_inputs, ext, extlen, NULL);
 		if(!real_display)
```

The print_tup_entry() command displays the path to a file relative to the root of the .tup hierarchy, and get_tup_top() is the CWD of the root of the hierarchy. The 'cmd' string here is the same string that ends up in the database, which is what ultimately gets executed by tup in the updater code.

**Comment by xpac27** [comment] 2018-01-31 22:46
I noticed, on my project, that generating a graph always produces a picture where leaf nodes are .cpp files and their parents are the corresponding compile command. This is exactly what we'd need (together with get_tup_top() and print_tup_entry()) to build the json.

However I found a quicker solution using [cdcc](https://github.com/gicmo/cdcc) and exporting the CXX env variable. Here's a simplified version of my Tupefile:

```
export CXX

: foreach src/.*cpp |> ${CXX} -c %f -o %o |> out/%B.o
```

I can either run `CXX=cdcc-clang++ && tup` or `export CXX=cdcc-clang++` then `tup` and generate the json by running `cdcc-gen src`. I find this setup flexible: anyone can set CXX to what best fits his needs. For ex `"ccache cdcc-clang++"` or just `"ccache clang++"` or even simply `clang++` if not intersted in the json nor caching or maybe `g++` if that makes sense. This way the Tupfile doesn't enforce the usage of tools such a ccache and cdcc and tup doesn't have to support functionalities that happen to be well handled by those tools.

I wonder if that approach would suit larger projects 😇

**Comment by ggsvr** [comment] 2021-06-04 22:22
Any updates?

**Comment by xpac27** [comment] 2021-06-05 19:37
I'm still using my workaround.

**Comment by gittup** [comment] 2021-06-05 23:42
Can you all test out the compiledb branch? https://github.com/gittup/tup/tree/compiledb

There are two main things to test here.

First:

It tries to add a 'tup compiledb' command, which should hopefully generate a compatible compile_commands.json at the top-level of the tup hierarchy of your project. I tested it with YCM, but I noticed it seems very finicky with the order of -c/-o flags & filenames. For example, '-c foo.c -o foo.o' produces an AST error, but '-c -o foo.o foo.c' works fine if it's at the end of the command string. (Tup itself builds with the former, so if you want to test it in the tup repo you'll need to change Tuprules.tup to put the flags in the correct order at the end of the rule.)

However, I don't particularly like the idea of the compiledb command. The problem is that it is essentially duplicating the information already contained in the .tup/db file, and in an inefficient format. For example, if we add a single flag to one commandline, .tup/db is updated with a single update statement, while the compile_commands.json format would need to be re-generated in its entirety (O(n) over the whole project). For larger projects this can be prohibitive to incremental development times.

The current implementation also does not automatically update the compile_commands.json, so you have to run 'tup compiledb' again to refresh it. Tup could of course generate this automatically after parsing, but because of the inefficiency of producing it I'm not very excited to do that. However, I would consider it if that makes tup more useful.

Second:

In my opinion, the correct approach is to have the tools query tup with the filename that they're interested in, and tup can return the command-line used. Essentially, this uses the tup database as the compilation database, instead of a separate, inefficient, redundant compile_commands.json file.

As an example, I tried to make a .ycm_extra_conf.py, which YCM can use instead of a compile_commands.json to get command-line info on-demand. This operates on the tup database directly using SQLite, but it may be more suitable to have a new "tup commandline [filename]" command that could be called by any tool (in which case .ycm_extra_conf.py would just shell out to tup instead of using the sqlite3 module).

Notes:

Both of these approaches require parser version 15, which is only on the compiledb branch. It should be safe to switch between parser version 14 (tup master) and 15 in your projects.

My preference would be to better support the second option going forward, perhaps with a builtin command to fetch the commandline for any file in the tup database. However, I only tested YCM, so I don't know how supported that is in other tools that use compile_commands.json files.

Let me know what issues you hit, and if you think the second option is totally infeasible.

**Comment by ggsvr** [comment] 2021-06-07 01:43
Correct me if I'm wrong, but from what I read, the second option relies on other tools implementing this interface, which if it were to happen, I don't think it would be a fast process. Plus I don't know how easy it would be to extend some of these tools.

On the other hand, I really like the idea of manually running tup compiledb, and not automatically, as it is not something **that** important, but more of a convenience. I would love to help develop this feature, but I'm a novice.

All in all, I personally think it would be better to focus on the compile_commands.json path, but again, I hardly know anything. That's just my two cents. 

Amazing project, btw.

**Comment by gittup** [comment] 2021-06-08 07:42
> Correct me if I'm wrong, but from what I read, the second option relies on other tools implementing this interface, which if it were to happen, I don't think it would be a fast process. Plus I don't know how easy it would be to extend some of these tools.

Yeah, I guess that's part of what I'm curious about. How many tools are there that make use of compile_commands.json? And do those tools have features like YouCompleteMe's .ycm_extra_conf.py or do they only support the json file?

I updated the branch to also add a 'tup commandline [filename]' to test. So 'tup commandline foo.c' will print the directory where the compiler runs on the first line, and the commandline on the second line. I updated the .ycm_extra_conf.py to use that. The only complexity that exists in that file now is to fix the -I flags to be full paths, since for some reason either ycm or the clang plugin has trouble with that (and the -c / -o flag ordering). Outside of that, the plugin could really just be a few lines of code.

In theory, if other programs also have a way to hook the commandline function, like a `string GetCommandLine(string filename)`, then it should just be able to shell out to `tup commandline` and return the result without needing to generate compile_commands.json at all.

> On the other hand, I really like the idea of manually running tup compiledb, and not automatically, as it is not something **that** important, but more of a convenience. I would love to help develop this feature, but I'm a novice.

It is implemented to be a manual process now on the compiledb branch - if you are able to tup compile locally you can give it a try and let me know what issues you hit. I haven't tested it extensively, so I wouldn't be surprised if there are problems.

**Comment by xpac27** [comment] 2021-06-08 20:39
> How many tools are there that make use of compile_commands.json?
For what I know most clang based tools require a compilation database, ex: [static analyzers](https://clang.llvm.org/extra/clang-tidy/), [code coverage tools](https://llvm.org/docs/CommandGuide/llvm-cov.html), [code formatters](https://clang.llvm.org/docs/ClangFormat.html), [language servers](https://clangd.llvm.org/) and [source code explorers](https://github.com/CoatiSoftware/Sourcetrail).

It seems today many editor (including vim, emacs, vscode, sublime) rely on LPS (language servers such as [clangd](https://clangd.llvm.org/)). [YCM can be setup to use a LPS](https://github.com/ycm-core/YouCompleteMe#plugging-an-arbitrary-lsp-server) too. For reference I'm using [coc](https://github.com/neoclide/coc.nvim/releases) in vim with clangd to write C++ and C.

Using a `.ycm_extra_conf.py` file with YCM is an alternative that exists since before language servers (AFAIK) so it doesn't require a compilation database making it possible to call `tup` on demand. This is great because it should scale with large projects and shouldn't require any additional steps in workflow (such as regenerating a json file), in opposition to generating a compilation database that can be slow and can require being manually generated. `cmake` re-generates the compilation database when compiling whenever the list of source files and/or compile commands have changed, but this adds to cmake's execution time whenever a file is renamed/add/removed so it's not an ideal approach. From my point of view a manual process is preferable though the approach you mentioned sounds like the ideal solution.

I don't think Clangd can use anything else than a compilation database :disappointed:. Even their [remote index server](https://clangd.llvm.org/remote-index.html), supposed to help on large projects, is just a way to share a common index build from a monolithic compilation database.

> fix the -I flags to be full paths, since for some reason either ycm or the clang plugin has trouble with that
This is probably a YCM problem when used in non-LPS mode. I generated a compilation database with `tup compiledb` from within the tup repro, started vim with coc and clangd could parse all the source files without a single errors showing up in the logs.

**Comment by xpac27** [comment] 2021-06-08 20:47
Maybe one could use a [configuration file](https://clangd.llvm.org/config.html) to prefix compile commands with call to tup and/or play with environment variables :thinking:

**Comment by ggsvr** [comment] 2021-06-08 22:12
Do you thing compiledb is ready to merge?

**Comment by gittup** [comment] 2021-06-11 23:20
> > How many tools are there that make use of compile_commands.json?
> 
> For what I know most clang based tools require a compilation database, ex: [static analyzers](https://clang.llvm.org/extra/clang-tidy/), [code coverage tools](https://llvm.org/docs/CommandGuide/llvm-cov.html), [code formatters](https://clang.llvm.org/docs/ClangFormat.html), [language servers](https://clangd.llvm.org/) and [source code explorers](https://github.com/CoatiSoftware/Sourcetrail).
> 
> It seems today many editor (including vim, emacs, vscode, sublime) rely on LPS (language servers such as [clangd](https://clangd.llvm.org/)). [YCM can be setup to use a LPS](https://github.com/ycm-core/YouCompleteMe#plugging-an-arbitrary-lsp-server) too. For reference I'm using [coc](https://github.com/neoclide/coc.nvim/releases) in vim with clangd to write C++ and C.
> 
> Using a `.ycm_extra_conf.py` file with YCM is an alternative that exists since before language servers (AFAIK) so it doesn't require a compilation database making it possible to call `tup` on demand. This is great because it should scale with large projects and shouldn't require any additional steps in workflow (such as regenerating a json file), in opposition to generating a compilation database that can be slow and can require being manually generated. `cmake` re-generates the compilation database when compiling whenever the list of source files and/or compile commands have changed, but this adds to cmake's execution time whenever a file is renamed/add/removed so it's not an ideal approach. From my point of view a manual process is preferable. The approach you mentioned sounds like the ideal solution, however a full project index is required for some LPS features to work (ex: find references, find definition/declaration, ...).
> 
> I don't think Clangd can use anything else than a compilation database disappointed. Even their [remote index server](https://clangd.llvm.org/remote-index.html), supposed to help on large projects, is just a way to share a common index built from a monolithic compilation database that gets updated periodically no_mouth.
> 
> > fix the -I flags to be full paths, since for some reason either ycm or the clang plugin has trouble with that
> 
> This is probably a YCM problem when used in non-LPS mode. I generated a compilation database with `tup compiledb` from within the tup repro, started vim with coc and clangd could index all the source files without a single errors showing up in the logs.

Thanks for the info! That is very helpful. Are you able to use 'tup compiledb' for your original projects instead of the compiler-wrapper work-around?

**Comment by gittup** [comment] 2021-06-11 23:22
> Do you think compiledb is ready to merge?

I'd like to add a few test cases before merging, and also any confirmations that it actually works and isn't totally broken for a few real-world use cases would be helpful :)

**Comment by Web-eWorks** [comment] 2021-06-13 21:42
Can confirm latest clone of the `compiledb` branch breaks with a CMake-style folder configuration (empty tup.config in `project-root/build/` folder):
```json
{
    "directory": "/home/sturnclaw/Documents/code/custom-lang/tis-tinyvm/[build] src",
    "command": "gcc -Wall -g -O1 -std=c99 -I../include -c array.c -o ../build/src/array.o",
    "file": "../../src/array.c"
},
```

Once the errant `[build] ` is removed from the directory path, the generated compile_commands file works out fairly well for my unsophisticated use-case.

**Comment by gittup** [comment] 2021-06-14 00:50
> Can confirm latest clone of the `compiledb` branch breaks with a CMake-style folder configuration (empty tup.config in `project-root/build/` folder):
> 
> ```json
> {
>     "directory": "/home/sturnclaw/Documents/code/custom-lang/tis-tinyvm/[build] src",
>     "command": "gcc -Wall -g -O1 -std=c99 -I../include -c array.c -o ../build/src/array.o",
>     "file": "../../src/array.c"
> },
> ```
> 
> Once the errant `[build] ` is removed from the directory path, the generated compile_commands file works out fairly well for my unsophisticated use-case.

Thanks for testing! I hadn't thought to try it with variants. Can you re-test with the latest compiledb branch? Both 'tup compiledb' and 'tup commandline' should support variants now I believe.

One thing to note with variants, is that if you have two different build configurations, both will end up in the same compile_commands.json. Would you normally expect each variant to have their own compile_commands.json? Or would you want to specify which variant to use in the 'tup compiledb' command? (Like 'tup compiledb build-release' or 'tup compiledb build-debug') Or something else?

**Comment by Web-eWorks** [comment] 2021-06-14 03:05
> One thing to note with variants, is that if you have two different build configurations, both will end up in the same compile_commands.json. Would you normally expect each variant to have their own compile_commands.json? Or would you want to specify which variant to use in the 'tup compiledb' command? (Like 'tup compiledb build-release' or 'tup compiledb build-debug') Or something else?

I'm afraid I don't use the variants feature enough to have a very insightful opinion. I mostly use it to get my artifacts out of the source tree and into a `build/` folder in lieu of a `tup clean` command. :smile: However, given that variants are mostly intended to be platform / build configuration specific as I understand them, and not to build specific parts of a project (for example, `frontend`, `backend`, `cli`) I think it makes sense to specify the variant you would like to generate a `compile_commands.json` for, with a sensible implicit default similar to what's selected when running `tup` normally.

**Comment by Web-eWorks** [comment] 2021-06-14 04:58
Can confirm the latest commit correctly (sort of) handles my use-case; with two variants I'm definitely seeing two differing set of command lines for each file; ideally tup only generates compile_commands from one variant.

If possible, I'd appreciate support for the ability to markup which tup rules contribute to a compile_commands.json; I could see this either taking the form of an input decorator like `foreach` or a command option (like `^b`, which I think is the better option). Ability to specify this markup in a macro would be amazing; I really like the terse nature of tup compared to Make.

For example:

```
compiledb foreach *.c |> gcc ... |> %B.o
```

Or, via command options so it can be defined in macros:

```
!cc = |> ^O gcc -c %f -o %o |> %B.o
foreach *.c |> !cc |>
```

**Comment by gittup** [comment] 2021-06-14 06:05
> Can confirm the latest commit correctly (sort of) handles my use-case; with two variants I'm definitely seeing two differing set of command lines for each file; ideally tup only generates compile_commands from one variant.

I've made it so 'tup compiledb' just generates a separate compile_commands.json for each variant in the root of the variant. I think that should work reasonably well?

> 
> If possible, I'd appreciate support for the ability to markup which tup rules contribute to a compile_commands.json; I could see this either taking the form of an input decorator like `foreach` or a command option (like `^b`, which I think is the better option). Ability to specify this markup in a macro would be amazing; I really like the terse nature of tup compared to Make.
> 
> For example:
> 
> ```
> compiledb foreach *.c |> gcc ... |> %B.o
> ```
> 
> Or, via command options so it can be defined in macros:
> 
> ```
> !cc = |> ^O gcc -c %f -o %o |> %B.o
> foreach *.c |> !cc |>
> ```

What is your goal for this? Is it just to get rid of extra commandlines from compile_commands.json to save space?

I was also wondering about limiting the list to only certain commands, but my initial thought was maybe it doesn't matter to have the extra commands in there in practice.

If it does matter, how reasonable would it be to have a fixed set of extensions to look for? Like if it just spit out entries for *.c / cc / cpp / mm / whatever, would that be what 99% of projects want anyway?

I think your ^O flag approach would be easiest to implement, but the downside would be even for a very straightforward project (eg: compiling *.cpp), you have to make that special annotation to support compiledb. Or maybe it could be a combination of a built-in set of extensions with a ^O flag for non-standard files?

**Comment by Web-eWorks** [comment] 2021-06-14 08:26
> I've made it so 'tup compiledb' just generates a separate compile_commands.json for each variant in the root of the variant. I think that should work reasonably well?

That works for me! I'm used to symlinking to CMake's compile_commands.json, so this shouldn't be a problem.

> What is your goal for this? Is it just to get rid of extra commandlines from compile_commands.json to save space?

Especially on larger projects, it'd be great to avoid the extra overhead from having every intermediate object file and other build-system managed file added to the compile_commands.json; I don't have a project that large using tup (yet), but I've worked with codebases like game engines and more complicated software where there are hundreds (or thousands) of C/C++ files that the language server needs to churn through. I'd consider it better from both a resource utilization and validation aspect to avoid writing totally-unused files to the compilation commands file, especially given the particularly lengthy nature of linker command lines. It's not a huge priority given e.g. clangd's multi-GB memory footprint, but something I'd appreciate having as a configurable option or even a sensible enforced default.

> I was also wondering about limiting the list to only certain commands, but my initial thought was maybe it doesn't matter to have the extra commands in there in practice.

In my small project, each intermediate object file takes ~280 bytes, whereas legitimate compilation entries are ~200 bytes. This is more than double the filesize just from linker command lines. If it's not infeasible to implement, I'm personally of the opinion that it is worth the effort to filter for specific file types. However, given that the file is usually parsed by an efficient JSON parser and loaded into some sort of hash table / database it's not *that* big of a concern if it would be a disproportionate amount of effort.

> If it does matter, how reasonable would it be to have a fixed set of extensions to look for? Like if it just spit out entries for *.c / cc / cpp / mm / whatever, would that be what 99% of projects want anyway?

Given that the compile_commands.json file is almost exclusively used by C/ObjC/C++ static analyzers as far as I know (because C is the last remaining major language family to not use some sort of standardized module system) this sounds like a very workable solution.

> I think your ^O flag approach would be easiest to implement, but the downside would be even for a very straightforward project (eg: compiling *.cpp), you have to make that special annotation to support compiledb. Or maybe it could be a combination of a built-in set of extensions with a ^O flag for non-standard files?

A combination of sensible defaults and manual control sounds like the best option to me! Feel free to assign whatever flag makes the most sense; I picked ^O partially at random.

**Comment by xpac27** [comment] 2021-06-18 18:47
> Are you able to use 'tup compiledb' for your original projects instead of the compiler-wrapper work-around?

It seems to work very well :slightly_smiling_face: I tested it on a few C and C++ projects with both clangd (in vim via coc), clang-tidy and Sourcetrail and it works, despite one problem with ${...} variables.

For ex the following rules:

```
export CC_FLAGS
export LD_FLAGS

CXX_FLAGS = -Wall -Wextra -Wpedantic -std=c++11 -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-newline-eof -Wno-padded -Wno-exit-time-destructors -Wno-c99-extensions
CXX_FLAGS += -g0 -O2
CXX_FLAGS += @(CC_FLAGS)
CXX_FLAGS += ${CC_FLAGS}


LD_FLAGS = -flto
LD_FLAGS += @(LD_FLAGS)
LD_FLAGS += ${LD_FLAGS}

!build_game = |> ^ %o^ ${CXX} $(CXX_FLAGS) -fPIC -Ilib/inc -Ilib/src -Iext -c %f -o %o |> out/obj/%B.o
: foreach lib/src/utils/*.cpp |> !build_game |> {game_objects}
: {game_objects} |> ^ %o^ ${CXX} $(LD_FLAGS) -shared %f -o %o |> out/libgame.so
```

produces:

```
{
    "directory": "/home/vinz/Github/TinyWorld/",
    "command": "${CXX} -Wall -Wextra -Wpedantic -std=c++11 -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-newline-eof -Wno-padded -Wno-exit-time-destructors -Wno-c99-extensions -g0 -O2  ${CC_FLAGS} -fPIC -Ilib/inc -Ilib/src -Iext -c lib/src/utils/Texture.cpp -o out/obj/Texture.o",
    "file": "lib/src/utils/Texture.cpp"
},
{
    "directory": "/home/vinz/Github/TinyWorld/",
    "command": "${CXX} -flto  ${LD_FLAGS} -shared out/obj/Application.o out/obj/Game.o out/obj/lodepng.o out/obj/ComponentManager.o out/obj/ComponentManagerBase.o out/obj/EntityManager.o out/obj/System.o out/obj/SystemStatistics.o out/obj/Camera.o out/obj/Cubemap.o out/obj/GBuffer.o out/obj/Mesh.o out/obj/MeshVertexArray.o out/obj/Model.o out/obj/Program.o out/obj/Quad.o out/obj/Renderer.o out/obj/Shader.o out/obj/MovementSystem.o out/obj/RenderSystem.o out/obj/Aggregator.o out/obj/Id.o out/obj/Log.o out/obj/Manifold.o out/obj/OBJ.o out/obj/PNG.o out/obj/Path.o out/obj/Random.o out/obj/Signal.o out/obj/Store.o out/obj/Texture.o out/obj/Utility.o -o out/libgame.so",
    "file": "out/obj/Game.o"
},
```

The above is from [this project](https://github.com/xpac27/TinyWorld).

**Comment by xpac27** [comment] 2021-06-18 19:18
> A combination of sensible defaults and manual control sounds like the best option to me! Feel free to assign whatever flag makes the most sense; I picked ^O partially at random.

I would be happy having to specify the flag without any default behavior. Listing files that should be considered defaults would be tedious and have to be maintained (for ex: LSP support way more languages than just C and C++ extending the list of defaults). I also think no defaults is more in line with Tup's approach to build system: doing just what the user wants, not more :slightly_smiling_face: but that's just my personal opinion.

> I've made it so 'tup compiledb' just generates a separate compile_commands.json for each variant in the root of the variant. I think that should work reasonably well?

I've got a project with default settings and 2 variants that overload or expend these settings, which I think follows Tup's manual's recommendations on variants :innocent: 

```
Tuprules.tup
Tupfile
variants/release.conf
variant/coverage.conf
src/...
```

Running:

```
tup compiledb
```

generates a compile db file in the root folder, then running

```
tup variant variants/release.config
tup variant variants/coverage.config
tup compiledb
```

again generates a compile db file in both the `build-release` and `build-coverage` folders, but the root level compile db is not updated, and running: 

```
tup compiledb release
```

updates the release variant's compile db only.

I would expect `tup compiledb` to either update all compile db files or only the non-variant version. I would prefer the later since it would give me more flexibility (I could still update all compile db files if I wanted by executing the command for each variant) though running `tup` builds all variant so i guess it would make sense if running `tup compiledb` updated all variant (and non-variant) compile db :stuck_out_tongue_closed_eyes:.

**Comment by gittup** [comment] 2021-06-20 02:20
> It seems to work very well slightly_smiling_face I tested it on a few C and C++ projects with both clangd (in vim via coc), clang-tidy and Sourcetrail and it works, despite one problem with ${...} variables.

Huh, that is an interesting pattern. So the ${...} construction is not something that is handled by the tup parser, but instead expanded by the shell. It may be confusing because {bin} is used as a way to group outputs in the parser, but it still gets highlighted in vim as if it's a variable (except for the $, which remains purple, since that is passed through unchanged). That's why tup is unable to expand it in the tup compiledb in this case.

I was going to suggest instead to use import, but I realized I never actually implemented that (https://github.com/gittup/tup/issues/103). I thought I did that a while ago :(.

In any case, now import is implemented, so you can read the value of the environment variable into the Tupfile, which works better with compiledb. Your example could look something like this:

```
import CXX=g++
import CC_FLAGS
import LD_FLAGS

CXX_FLAGS = -Wall -Wextra -Wpedantic -std=c++11 -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-newline-eof -Wno-padded -Wno-exit-time-destructors -Wno-c99-extensions
CXX_FLAGS += -g0 -O2
CXX_FLAGS += @(CC_FLAGS)
CXX_FLAGS += $(CC_FLAGS)


LD_FLAGS += -flto
LD_FLAGS += @(LD_FLAGS)

!build_game = |> ^j %o^ $(CXX) $(CXX_FLAGS) -fPIC -Ilib/inc -Ilib/src -Iext -c %f -o %o |> out/obj/%B.o
: foreach lib/src/utils/*.cpp |> !build_game |> {game_objects}
: {game_objects} |> ^ %o^ $(CXX) $(LD_FLAGS) -shared %f -o %o |> out/libgame.so
```

CXX defaults to g++ if unset, and CC_FLAGS and LD_FLAGS are empty if unset in the environment.

**Comment by gittup** [comment] 2021-06-20 02:32
> > A combination of sensible defaults and manual control sounds like the best option to me! Feel free to assign whatever flag makes the most sense; I picked ^O partially at random.
> 
> I would be happy having to specify the flag without any default behavior. Listing files that should be considered defaults would be tedious and have to be maintained (for ex: LSP support way more languages than just C and C++ extending the list of defaults). I also think no defaults is more in line with Tup's approach to build system: doing just what the user wants, not more but that's just my personal opinion.

That makes sense to me, though if there is more support for adding a set of defaults, I don't have a problem adding that too. I changed the branch so that it only writes entries for commands that have the ^j flag set (j for json, but I could also do 'd' for database, or something else :).

> I've got a project with default settings and 2 variants that overload or expend these settings, which I think follows Tup's manual's recommendations on variants innocent
> 
> ```
> Tuprules.tup
> Tupfile
> variants/release.conf
> variant/coverage.conf
> src/...
> ```
> 
> Running:
> 
> ```
> tup compiledb
> ```
> 
> generates a compile db file in the root folder, then running
> 
> ```
> tup variant variants/release.config
> tup variant variants/coverage.config
> tup compiledb
> ```
> 
> again generates a compile db file in both the `build-release` and `build-coverage` folders, but the root level compile db is not updated, and running:
> 
> ```
> tup compiledb release
> ```
> 
> updates the release variant's compile db only.
> 
> I would expect `tup compiledb` to either update all compile db files or only the non-variant version. I would prefer the later since it would give me more flexibility (I could still update all compile db files if I wanted by executing the command for each variant) though running `tup` builds all variant so i guess it would make sense if, in the context of the above example, running `tup compiledb` updated all 3 compile db files stuck_out_tongue_closed_eyes.

I'm not sure this would be easy to do. Without any variants specified, tup defaults to building in-tree, with the build root the same as the root of the project. If you later enable a variant, the default in-tree variant is then disabled (all commands and output files are removed from the database and the tree). So, there's no longer any information in the database for tup to continue to write to the "default" in-tree variant once a variant is enabled. In your case you either have 1 in-tree default build, or 2 out-of-tree variant builds (release & coverage), but never all 3 at once.

As far as the file sitting around and/or not getting updated automatically, that is the downside of making it a manual command instead of something more like a regular tup output (where it would be automatically updated when an input changes). In this case, the input is essentially the database itself, so it would need to be re-written from scratch every time a Tupfile gets re-parsed essentially. I'm not sure there's really a good solution here that is both user-friendly and performant, since it seems the design of compile_commands.json precludes it.

Hopefully the addition of `tup commandline` as well (or something similar) will make it easier for a language server to interact with the tup database directly instead of via the intermediary json representation.

**Comment by xpac27** [comment] 2021-06-20 14:04
> In your case you either have 1 in-tree default build, or 2 out-of-tree variant builds (release & coverage), but never all 3 at once.

I see. I use the default build as a debug build and a variant for release, but I could always make a debug variant if I wanted to be able to switch easily between building release or debug. Then the current `tup compiledb`'s behavior regarding variant makes sense.

Sounds good about defaults :+1: :slightly_smiling_face: 

Good to know about ${...}! my bad for miss-understanding the manual. I'll use your suggestion :+1: 

> As far as the file sitting around and/or not getting updated automatically, that is the downside of making it a manual command instead of something more like a regular tup output (where it would be automatically updated when an input changes). In this case, the input is essentially the database itself, so it would need to be re-written from scratch every time a Tupfile gets re-parsed essentially. I'm not sure there's really a good solution here that is both user-friendly and performant, since it seems the design of compile_commands.json precludes it.

I totally agree. For reference `cmake` updates the compile db file automatically (as far as I remember) and `ninja` uses your approach of a manual rebuild. In my opinion a manual rebuild is much preferable. The reason why I'm not using cmake and prefer tup (or ninja) is because I want a very quick feedback. My use-case is whenever saving a file, re-building affected objects and running impacted unit tests executables. Tup and [entr](https://github.com/clibs/entr) are the best tools for this job (that i know of).

> Hopefully the addition of tup commandline as well (or something similar) will make it easier for a language server to interact with the tup database directly instead of via the intermediary json representation.

I hope so too :smile: it's a unique idea that helps tup stand out.

Maybe [clang](https://clang.llvm.org/docs/JSONCompilationDatabase.html#supported-systems) and [clangd](https://clangd.llvm.org/installation.html) should start listing tup in their documentation once this is released. Other clang/compiledb based tool could do that too. That would help tup's reputation :innocent: do you think this is a good idea?

**Comment by gittup** [comment] 2021-06-21 19:38
> > Hopefully the addition of tup commandline as well (or something similar) will make it easier for a language server to interact with the tup database directly instead of via the intermediary json representation.
> 
> I hope so too smile it's a unique idea that helps tup stand out.

On this note, should 'tup commandline' output the same JSON format (to stdout) that compile_commands.json uses? Right now it just prints the working directory on one line and the commandline on a second line.

> Maybe [clang](https://clang.llvm.org/docs/JSONCompilationDatabase.html#supported-systems) and [clangd](https://clangd.llvm.org/installation.html) should start listing tup in their documentation once this is released. Other clang/compiledb based tool could do that too. That would help tup's reputation innocent do you think this is a good idea? there's [that page](https://sarcasm.github.io/notes/dev/compilation-database.html#build-systems-and-compilers) too.

That would be nice :). I think once this is finalized and merged I should be about ready to make a v0.8 release.

**Comment by Web-eWorks** [comment] 2021-06-21 19:45
> On this note, should 'tup commandline' output the same JSON format (to stdout) that compile_commands.json uses? Right now it just prints the working directory on one line and the commandline on a second line.

Why not both? By default it prints working directory and commandline, but if you pass `tup commandline -j <file>` it prints the compile_commands-format JSON?

**Comment by gittup** [comment] 2021-06-22 23:00
> > On this note, should 'tup commandline' output the same JSON format (to stdout) that compile_commands.json uses? Right now it just prints the working directory on one line and the commandline on a second line.
> 
> Why not both? By default it prints working directory and commandline, but if you pass `tup commandline -j <file>` (or `tup commandline --json <file>`) it prints the compile_commands-format JSON?

I suppose just to keep things simple :). If programs using compile_commands.json are already set to import that particular json format, it might be easier to switch them to a 'tup commandline' that exports the same type of information.

**Comment by gittup** [comment] 2021-06-24 18:07
I updated the branch with some documentation in the man page, and made 'tup commandline' output JSON as well. (This helps if you do 'tup commandline foo.c bar.c baz.c', since each entry is then clearly delineated). Anything else I missed? If it seems to work ok for you all, I'll plan to merge it next week sometime.

**Comment by Web-eWorks** [comment] 2021-06-24 19:39
Looking good! I'll give the updated branch a whirl sometime over the weekend and let you know if there are any issues.

**Comment by gittup** [comment] 2021-06-24 19:40
> Looking good! I'll give the updated branch a whirl sometime over the weekend and let you know if there are any issues.

Sounds great, thanks!

**Comment by xpac27** [comment] 2021-06-25 08:31
I gave it an other try and implemented your suggestion (using `import`) and everything works perfectly. Sourcetrail and clangd could index my project and reported zero errors :+1:

**Comment by gittup** [comment] 2021-06-28 23:23
Ok, it's merged to master!

**Closed by gittup** 2021-06-28 23:23 UTC
