### ISSUE TITLE
Hello World fails on Windows

### ISSUE THREAD

**Issue by marler8997** [gittup/tup#219] opened 2015-02-03 22:01 UTC
tup fails saying that is was unable to save dependencies after invoking a compiler on windows to create a .exe file.

On Windows (tup v0.7.3-18-g8e63ea4)
```
dir
    test.c
    Tupfile
```
test.c
----
```C
#include <stdio.h>
int main(int argc, char* argv[])
{
  printf("Hello, World\n");
  return 0;
}
```
Tupfile
----
```
: test.c |> cl /c test.c |> test.obj
: test.obj |> cl test.obj |> test.exe
```

```batch
REM run from Visual Studio Command prompt (to have the "cl" program in the path)
> tup init
> tup upd
[ tup ] [0.007s] Scanning filesystem...
[ tup ] [0.020s] Reading in new environment variables...
[ tup ] [0.030s] Parsing Tupfiles...
 1) [0.004s] .
 [ ] 100%
[ tup ] [0.039s] No files to delete.
[ tup ] [0.041s] Generating .gitignore files...
[ tup ] [0.049s] Executing Commands...
 1) [0.061s] cl /c test.c
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

test.c
* 2) cl test.obj
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

Microsoft (R) Incremental Linker Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj
Unable to retrieve WOW64 info
 *** tup errors ***
tup error: Expected to write to file 'test.exe' from cmd 24 but didn't
 *** Command ID=24 ran successfully, but tup failed to save the dependencies.
 [  ] 100%
 *** tup: 1 job failed.
```

The `test.exe` program was created but tup still shows an error.  I just got started with tup so I don't know what's going on.  Is this a bug or am I doing something wrong?

Note: same error when using dmd (The D Language compiler).

**Comment by KamilSzczygiel** [comment] 2015-02-06 19:50
If your tools are 32-bits and you don't do anything fancy, try these two things:
- try to use gcc
- try an older version of tup

**Comment by marler8997** [comment] 2015-02-06 21:34
I get the same error with gcc

Tupfile
---
: test.c |> gcc -o test.exe %f |> test.exe

```
c:\Temp\testtup>tup
tup
[ tup ] [0.009s] Scanning filesystem...
[ tup ] [0.019s] Reading in new environment variables...
[ tup ] [0.046s] Parsing Tupfiles...
 100% 1) [0.002s] .
[ tup ] [0.050s] No files to delete.
[ tup ] [0.050s] Generating .gitignore files...
[ tup ] [0.056s] Executing Commands...
* 100% 1) gcc -o test.exe test.c
Unable to retrieve WOW64 info
Unable to retrieve WOW64 info
Unable to retrieve WOW64 info
 *** tup errors ***
tup error: Expected to write to file 'test.exe' from cmd 20 but didn't
 *** Command ID=20 ran successfully, but tup failed to save the dependencies.
 *** tup: 1 job failed.
```

The test.exe file is created but tup still says it failed to save the dependencies.  When I run the command `gcc -o test.exe test.c` it works and compiles fine, but tup is still failing.  What is happening?

**Comment by KamilSzczygiel** [comment] 2015-02-06 21:49
Try an older version of tup - I'm not on Windows right now, but it all worked flawlessly some time ago. Maybe recent addition of 64-bit support for Windows broke something? Try a version from around September - I was using it myself and it worked fine.

**Comment by gittup** [comment] 2015-11-30 21:39
I'm not able to reproduce this. I tried both v0.7.3-18-g8e63ea4 as well as the latest master, and VC2010 before and after SP1 (cl.exe version 16.00.30319.01 and 16.00.40219.01). Is anyone still hitting this? Maybe there are some other system differences that cause it.

**Comment by gittup** [comment] 2015-12-01 19:01
I think this is fixed by commit 194f2e7d848902bc7b60dfeb4f6948494c311266. The problem is that if tup32detect.exe isn't in the PATH, it was failing to run and resulted in the WOW64 info error message.

**Comment by gittup** [comment] 2016-01-07 21:43
Please reopen if you are still having issues with this, but if it was the tup32detect.exe issue then it should be fixed.

**Closed by gittup** 2016-01-07 21:43 UTC

**Comment by Flawe** [comment] 2016-02-03 05:32
I'm having this exact issue on Windows 7 64bit. I got tup32detect.exe in my path. tup-v0.7.3-76-ge8b4d39.zip 2015-11-24 22:57 is the last version that works fine, anything newer and I get the "Unable to retrieve WOW64 info" error and the job fails.

**Comment by FreddieChopin** [comment] 2016-02-03 07:12
@Flawe - why don't you try with a more recent version than yours?

**Comment by FreddieChopin** [comment] 2016-02-03 07:14
Please post exact info about your setup (system PATH, where tup is, what tool are you trying to use, where it is, ...) so that your problem could be recreated.

**Comment by Flawe** [comment] 2016-02-03 18:18
Why does it matter where tup is if that folder is in the path variable? And what do you mean what tool I'm trying to use? I just followed the steps on the tup website and the "tup upd" or just "tup" command failed when I got to that step with the "WOW64" error mentioned above.

**Comment by FreddieChopin** [comment] 2016-02-03 19:33
Apparently something matters, because in here it works perfectly fine. But if you don't wish to share any of that secret information, then I guess you cannot expect anyone to help you.

**Comment by jbe** [comment] 2016-06-11 10:51
I am having the same problem here on win10/vs2015. Except here tup is not detecting files produced by `cl`, while `gcc` + mingw works fine.

Here's the output and some info: https://gist.github.com/jbe/a859d93f0e946dcef7f3197c3b771b24

I also tried v0.7.1-12-g82dac2f and v0.7.3-4-g1a8d07e, but neither of them would run. ("The program can't start because tup-dllinject.dll is missing..." -- it is not missing, it is right next to `tup.exe` in `system32`).
