### ISSUE TITLE
Variants break debug info

### ISSUE THREAD

**Issue by Ralith** [gittup/tup#229] opened 2015-02-26 04:04 UTC
When compiling a C/C++ project with variants, gdb can't find source files. The chroot ^-flag has no effect on this, because the debug info is written by a compiler that thinks source files exist in the variant directories. The only solution I've found is manually adding every single directory containing source files to GDB's search path, which is tedious and breaks down when multiple files in different locations have the same name.

Instead of executing the compiler in the variant directories and using FUSE to make the input files appear to be present, would it be possible to execute the compiler in the source directories and use FUSE to redirect the output files? This would make variants completely transparent to debug info.

Another less magical solution would be to not unify the source and variant directory trees at all, instead passing the real path to the source file while executing inside the variant directory.

**Comment by tiffany352** [comment] 2015-03-13 23:33
This affects me as well. The problem is even more annoying in LLDB, which doesn't have a 'dir' command to add a search path like GDB does.

**Comment by p2rkw** [comment] 2015-03-14 22:27
I have exactly same problem with tup.

**Comment by banks** [comment] 2015-03-25 14:00
+1 Been trying to figure out what is going on for a while. Variants seem to be more or less essential to any real build for debug vs release compile options. To not be able to debug your debug build is certainly less than ideal :).

**Comment by banks** [comment] 2015-03-25 15:49
I should add that I'm on OS X which has whoel new workd of pain with debug symbols in separate dsym bundles.

@Ralith could you please give a simple example of you workaround with `dir`. I realise it's probably something to do with the fact that gdb is relying on dsymutil to try to get the debug info and so fails to find the object files even when I tried manually specifying with `dir` or `set substitute-path` commands, but it would be useful to confirm it wasn't some dumb mistake. Are you on OS X? I assume not...

**Comment by banks** [comment] 2015-03-25 16:02
Hmm actually, I'm not convinced we are all talking about the same problem.

Even without variants debugging is still broken on OS X because the o files are linked into binary with paths that look like: `/Users/banks/src/banks/myproject/.tup/mnt/@tupjob-18095/Users/banks/src/banks/myproject/foo.o` which dsymutil can't find when trying to extract the debug info - even though the actual o files are still in the directory tree.

**Comment by fourier** [comment] 2015-04-09 09:14
I'm having the same problem on OSX. Works fine on Linux.

**Comment by gittup** [comment] 2015-11-05 19:35
I've pushed the explicit-variant branch (https://github.com/gittup/tup/tree/explicit-variant) which removes the filesystem overlaying, and instead redirects the outputs to the variant directory by changing the value of %o and such. See https://github.com/gittup/tup/issues/70#issuecomment-154150507 for some more info. I'd appreciate feedback if that helps address this issue!

**Comment by xguerin** [comment] 2015-12-19 22:08
I gave it a shot today as I am hitting the same problem as @banks . It does not seem to address the object paths:

```
Reading symbols from build-dbg/main...
warning: `/Sandbox/test/.tup/mnt/@tupjob-33/Sandbox/test/build-dbg/main.o': can't open to read symbols: No such file or directory.
(no debugging symbols found)...done.
```

**Comment by gittup** [comment] 2015-12-21 15:32
On OSX you'll still need to use the ^c flag to run in a chroot, otherwise the .tup/mnt path will be visible. The explicit-variant branch is necessary because while the ^c flag makes the .tup/mnt path go away, the filesystem overlay used by the current variant implementation means that the compiler doesn't know the actual underlying path of the files. When tools outside of tup are used, they no longer know about the overlay, so they can't find the actual files.

**Comment by ccostes** [comment] 2016-04-06 01:20
Having an odd issue with the explicit-variant branch. Cloned the latest, built tup, and created a simple test project with one .cpp file. It works fine with no variant, but when I add a variant it throws errors indicating that the output wasn't where it expected it. 

Tupfile:
```
include_rules

: example1.cpp |> !cxx |> 
: example1.o |> !link |> program
```

Tuprules.tup
```
!cxx = |> g++ -c %f -o %B.o |> %B.o
!link = |> g++ %f -o %o |> 
```

Console log of the test:
```
$ ls
example1.cpp  Tupfile  Tuprules.tup
$ tup
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.010s] Reading in new configuration/environment variables...
 1) delete variant: build-test/tup.config
 [ ] 100%
[ tup ] [0.012s] Parsing Tupfiles...
 1) [0.002s] .
 [ ] 100%
[ tup ] [0.014s] No files to delete.
[ tup ] [0.014s] Generating .gitignore files...
[ tup ] [0.015s] Executing Commands...
 1) [0.056s] g++ -c example1.cpp -o example1.o
 2) [0.054s] g++ example1.o -o program
 [  ] 100%
[ tup ] [0.129s] Updated.
$ ls
example1.cpp  example1.o  program  Tupfile  Tuprules.tup
$ tup variant test
tup: Added variant 'build-test' using config file 'test'
$ tup build-test/
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.008s] Reading in new configuration/environment variables...
 1) new variant: [build-test] tup.config
 [ ] 100%
[ tup ] [0.010s] Deleting 2 commands...
 1) rm: example1.o
 2) rm: program
 [  ] 100%
[ tup ] [0.013s] Parsing Tupfiles...
 1) [0.002s] [build-test] .
 [ ] 100%
[ tup ] [0.016s] No files to delete.
[ tup ] [0.016s] Generating .gitignore files...
[ tup ] [0.017s] Executing Commands...
* 1) [build-test] g++ -c example1.cpp -o example1.o
 *** tup errors ***
tup error: File '/home/ccostes/gcov/example1.o' was written to, but is not in .tup/db. You probably should specify it as an output
tup error: Expected to write to file 'example1.o' from cmd 25 but didn't
 *** Command ID=25 ran successfully, but tup failed to save the dependencies.
 [  ]  50%
 *** tup: 1 job failed.
```

This seems like a pretty obvious bug, and considering you said you were able to build tup with this variant, @gittup , I feel like I must be doing something dumb. Any ideas?

**Comment by superworm** [comment] 2016-05-01 19:49
Try changing the first %B.o to %o:

!cxx = |> g++ -c %f -o %B.o |> %B.o

**Comment by ccostes** [comment] 2016-05-02 13:28
Alright cool, that change does fix the error in the example. The original reason I was trying to use that syntax was that I am trying to compile with code-coverage and needed to specify additional outputs to tup without it substituting them into the command. On a hunch I tried using the same syntax as the "order-only inputs" and it works!

Thanks!

For those trying to do the same thing, here's the rule that I ended up using:
`!cxx = |> g++ -fprofile-arcs -ftest-coverage -fPIC -O0 -c %f -o %o |> %B.o | %B.gcno`

**Comment by ChengCat** [comment] 2019-01-24 09:45
I hope tup can spawn a shell, in which the underlying file system is transparently altered the same way as compile commands see it. To be specific, one can run something like `tup shell xx-variant`, start gdb in that shell, and gdb would automatically find the source files.

**Comment by ratmice** [comment] 2019-05-20 16:40
IIUC there is a gcc/clang option which can be used to map
the fuse filesystem path to the original sources -fdebug-prefix-map=old=new
https://gcc.gnu.org/onlinedocs/gcc-4.8.4/gcc/Debugging-Options.html#index-fdebug-prefix-map-569

**Comment by gittup** [comment] 2021-05-17 18:39
Explicit variants have been merged, which should finally fix this issue. Feel free to re-open if you're still hitting it.

**Closed by gittup** 2021-05-17 18:39 UTC
